# Generated by Django 4.2.6 on 2024-03-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='followers_set',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
