# Generated by Django 4.2.6 on 2024-03-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_profile_image_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, unique=True, upload_to='my_picture'),
        ),
    ]
